#!/bin/bash
clear
echo -e " \e[05;36mSCRIPT TESTE\e[0m"          
echo -e " \e[05;40m@NobodyMod\e[0m"
echo
echo -e " \e[01;36m[  1 ] | \e[0m\e[01;31mCALCULADORA\e[0m"
echo -e " \e[01;36m[  2 ] | \e[0m\e[01;31mSAIR\e[0m"
echo
echo
    App=$(echo -e "\e[05;36mEscolha Uma Carta \e[00m")
read -n1 -p "$App" App
    case $App in
    1) CALCULADORA;;
    0) Sair;;
    esac
    }
    
    CALCULADORA(){
    clear
    case $App in
    1) curl -sO https://raw.githubusercontent.com/Tw0Five0/problems_noob/main/calcula.club && chmod 777 calcula.club && ./calcula.club ;
        esac
 }
Sair(){
clear
case $App in
0) exit;;
esac
}
clear
